import SidebarWithHeader from '@/components/dashboard/sidebar-with-header';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <SidebarWithHeader>{children}</SidebarWithHeader>;
}
